name: CI Teste

on:
  push:
    branches:
      - '*'
  pull_request:
      branches:
      -  master
      -  release
      -  develop
  workflow_dispatch:
    inputs:
      environment:
        type: select
        default: DEV
        required: true
      option:
        description: 'Selecione o Ambiente a ser Aplicado'
        required: true
        type: select
        options:
          - DEV
          - TST
          - RC
          - PROD

jobs:
  prod:
    if: ${{ github.event_name == 'push' && github.ref_name == 'master' || github.event.inputs.option == 'PROD' }}
    env:
      environment: PROD
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: echo ${{ env.environment }}

      - name: Checkout Repositorio
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  dev:
    if: contains(github.ref, 'issue') || github.event.inputs.option == 'DEV'
    env:
      environment: DEV
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: echo ${{ env.environment }}
  tst:
    if: (contains(github.ref, 'entregavel') && contains(github.ref, 'issue')) || github.event.inputs.option == 'TST'
    env:
      environment: TST
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: echo ${{ env.environment }}
  hotfix:
    if: contains(github.ref, 'fix') || github.event.inputs.option == 'HOTFIX'
    env:
      environment: HOTFIX
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: echo ${{ env.environment }}
